export const forgedItems = [
  {
    name: "Ashenblade of the Abyss",
    type: "weapon",
    description:
      "Forged in dragonfire, this blade thirsts for the souls of the fallen.",
    materials: [
      { name: "Obsidian Steel", quantity: 3 },
      { name: "Abyssal Ember", quantity: 1 },
      { name: "Soul Dust", quantity: 2 },
    ],
    price: 4800,
    creation_time_hours: 14,
    rarity: "epic",
    min_level: 18,
    modifiers: {
      strength: 10,
      dexterity: 6,
      fire_damage: "+30%",
      lifesteal: "5%",
    },
  },
  {
    name: "Helm of the Whispering Depths",
    type: "helmet",
    description: "Whispers from the deep grant wisdom to the bearer.",
    materials: [
      { name: "Darksteel Plate", quantity: 2 },
      { name: "Echo Crystal", quantity: 1 },
      { name: "Sealed Whispers", quantity: 1 },
    ],
    price: 3300,
    creation_time_hours: 8,
    rarity: "rare",
    min_level: 15,
    modifiers: {
      intelligence: 8,
      constitution: 3,
      mana_regen: "+12%",
      mind_resistance: "+20%",
    },
  },
  {
    name: "Titanborn Aegis",
    type: "shield",
    description:
      "This colossal shield was molded from the bones of an earth titan.",
    materials: [
      { name: "Titan Bone", quantity: 2 },
      { name: "Runed Granite", quantity: 3 },
      { name: "Living Core", quantity: 1 },
    ],
    price: 4000,
    creation_time_hours: 11,
    rarity: "epic",
    min_level: 17,
    modifiers: {
      defense: 36,
      constitution: 7,
      earth_resistance: "+40%",
      knockback_resist: "+15%",
    },
  },
  {
    name: "Gauntlets of Blazing Wrath",
    type: "armor",
    part: "hands",
    description: "They ignite with fury when the wearer is struck.",
    materials: [
      { name: "Molten Iron", quantity: 2 },
      { name: "Firebound Leather", quantity: 1 },
      { name: "Wrath Essence", quantity: 1 },
    ],
    price: 2900,
    creation_time_hours: 7,
    rarity: "rare",
    min_level: 14,
    modifiers: {
      strength: 5,
      fire_damage: "+15%",
      retaliation_damage: "10 fire",
    },
  },
  {
    name: "Boots of Emberwind",
    type: "armor",
    part: "feet",
    description: "Light as smoke, these boots leave trails of flame.",
    materials: [
      { name: "Ashhide Leather", quantity: 2 },
      { name: "Wind Essence", quantity: 1 },
      { name: "Cinder Thread", quantity: 1 },
    ],
    price: 2500,
    creation_time_hours: 6,
    rarity: "uncommon",
    min_level: 12,
    modifiers: {
      dexterity: 6,
      movement_speed: "+20%",
      fire_resistance: "+10%",
    },
  },
  {
    name: "Cuirass of Eternal Flame",
    type: "armor",
    part: "chest",
    description:
      "Burns with a flame that never dies, protecting its bearer from cold and fear.",
    materials: [
      { name: "Forged Flameplate", quantity: 3 },
      { name: "Heartfire Crystal", quantity: 1 },
      { name: "Runic Binding", quantity: 2 },
    ],
    price: 5000,
    creation_time_hours: 13,
    rarity: "epic",
    min_level: 19,
    modifiers: {
      defense: 28,
      fire_resistance: "+50%",
      fear_resist: "+100%",
      constitution: 5,
    },
  },
  {
    name: "Crown of Ember Kings",
    type: "helmet",
    description: "Once worn by a monarch who ruled a kingdom of flame.",
    materials: [
      { name: "Flamegold", quantity: 2 },
      { name: "Phoenix Feather", quantity: 1 },
      { name: "Royal Crest", quantity: 1 },
    ],
    price: 6000,
    creation_time_hours: 10,
    rarity: "legendary",
    min_level: 20,
    modifiers: {
      charisma: 10,
      fire_damage: "+20%",
      leadership_aura: "+10% allies' damage",
    },
  },
];
